FROM golang



RUN go get "github.com/gorilla/mux"
RUN go get "github.com/gorilla/handlers"
RUN go get "gopkg.in/gorethink/gorethink.v3"
ADD ask-server /go/src/github.com/ComputePractice2017/ask-server 
RUN go install github.com/ComputePractice2017/ask-server

ENTRYPOINT /go/bin/ask-server

ENV RETHINKDB_HOST db

EXPOSE 8000